---

- hosts: all
  become: false
  tasks:
  - name: Finding the processes on the node
    ansible.builtin.find:
      paths: /proc
      file_type: file
      patterns: status
      recurse: true
    register: found_files

  - name: Process the processes
    filter_files:
    delegate_to: localhost
    run_once: true
    register: filtered_files

  - name: Debug
    ansible.builtin.debug:
      var: filtered_files.paths

  - name: Fetch all status files
    ansible.builtin.fetch:
      dest: "files/{{ item | regex_replace('/proc/(\\d+)/status', '\\1') }}"
      src: "{{ item }}"
      flat: true
    loop: "{{ filtered_files.paths }}"
    failed_when: false

