---

- hosts: all
  become: false
  tasks:
  - name: Finding the processes on the node
    ansible.builtin.find:
      paths: /proc
      file_type: file
      patterns: status
      recurse: true
    register: found_files

  - name: Process the processes
    filter_files:
    delegate_to: localhost
    register: filtered_files

  - name: Fetch all status files
    ansible.builtin.fetch:
      dest: "files/{{ ansible_host }}/{{ item | regex_replace('/proc/(\\d+)/status', '\\1') }}"
      src: "{{ item }}"
      flat: true
    loop: "{{ filtered_files.paths }}"
    failed_when: false
    when: true

  - name: Parse all status files and create the json needed
    ansible.builtin.script: parse_status.py
    args:
      executable: python
    delegate_to: localhost

  - name: Debug
    ansible.builtin.debug:
      var: ansible_host

